# Generated by Django 5.0.2 on 2024-02-20 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_todoitem_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='isdone',
            field=models.BooleanField(default=False),
        ),
    ]
